create database customer_behavior

select * from customer_data

select top 20 * from customer_data

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS REVENUE FROM customer_data
GROUP BY gender
--helps the business to generate better targeted campaigns for each group


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select * from customer_data
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_data)


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, review_rating from customer_data
where review_rating >= (select AVG(review_rating) from customer_data) -- wrong query

-- right query
select top 5 item_purchased, ROUND(AVG(review_rating),2) as avg_rating from customer_data
group by item_purchased
order by avg_rating desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select avg(purchase_amount) as avg_purchase, shipping_type from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type



--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
AVG(purchase_amount) as avg_amt,
SUM(purchase_amount) as total_revenue
from customer_data
group by subscription_status


--Q6. Which 10 products have the highest percentage of purchases with discounts applied?
-- Which products rely heavily on discount to sell

select top 10 item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases, 
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	ELSE 'LOYAL CUSTOMER'
	END AS customer_segment
from customer_data
)

select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment
order by number_of_customers desc



--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;



--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue desc;